[package]
name = "wat3rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.16.0"
futures = "0.3.30"
wgpu = "0.20.0"
winit = "0.30.0"
